package plantsketch.threeDee;

import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.geometry.Point3D;
import javafx.scene.*;
import javafx.scene.image.PixelWriter;
import javafx.scene.image.WritableImage;
import javafx.scene.input.KeyCode;
import javafx.scene.input.MouseButton;
import javafx.scene.input.ScrollEvent;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.scene.paint.PhongMaterial;
import javafx.scene.shape.DrawMode;
import javafx.scene.shape.MeshView;
import javafx.scene.shape.TriangleMesh;
import javafx.scene.transform.Rotate;
import javafx.scene.transform.Translate;
import javafx.stage.Stage;

import java.awt.image.BufferedImage;

/**
 * Single-file JavaFX example that builds an interactive 3D terrain using TriangleMesh.
 *
 * Features:
 * - Height generated by Perlin noise.
 * - Color texture created from heightmap.
 * - Smooth camera controls (orbit, pan, zoom).
 * - Adjustable LOD via grid size and height scaling.
 *
 * Requirements: Java 11+ (JavaFX on module path or classpath).
 */
public class ThreeDeeOld extends Application {

    private static final int SIZE = 200; // grid size (vertices per side)
    private static final float SCALE = 6f; // spacing between vertices
    private static final float HEIGHT_SCALE = 120f; // vertical exaggeration

    private double anchorX, anchorY;
    private double anchorAngleX = 20;
    private double anchorAngleY = -45;
    private final Rotate rotateX = new Rotate(20, Rotate.X_AXIS);
    private final Rotate rotateY = new Rotate(-45, Rotate.Y_AXIS);

    private final Translate cameraTranslate = new Translate(0, 0, -800);
    private PerspectiveCamera camera;

    @Override
    public void start(Stage primaryStage) {
        Group root3D = new Group();

        // Create terrain mesh and texture
        float[][] heightGrid = generateHeightGrid(SIZE, SIZE, 0.009f, 6);
        TriangleMesh mesh = buildTerrainMesh(heightGrid, SCALE);
        WritableImage tex = buildTextureFromHeights(heightGrid);

        PhongMaterial material = new PhongMaterial();
        material.setDiffuseMap(tex);

        MeshView terrain = new MeshView(mesh);
        terrain.setCullFace(javafx.scene.shape.CullFace.NONE);
        terrain.setMaterial(material);
        terrain.setDrawMode(DrawMode.FILL);

        // Center terrain
        terrain.setTranslateX(-((SIZE - 1) * SCALE) / 2.0);
        terrain.setTranslateZ(-((SIZE - 1) * SCALE) / 2.0);

        root3D.getChildren().add(terrain);

        // Lights
        PointLight light = new PointLight(Color.WHITE);
        light.setTranslateX(-1000);
        light.setTranslateY(-1000);
        light.setTranslateZ(-1000);
        AmbientLight ambient = new AmbientLight(Color.color(0.35, 0.35, 0.38));
        root3D.getChildren().addAll(light, ambient);

        // Camera
        SubScene subScene = setupSubScene(root3D);

        StackPane root = new StackPane(subScene);
        Scene scene = new Scene(root, 1200, 800, true);

        setupControls(scene, root3D, terrain);

        primaryStage.setTitle("JavaFX 3D Terrain Demo");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private SubScene setupSubScene(Group root3D) {
        Group cameraGroup = new Group();
        camera = new PerspectiveCamera(true);
        camera.setNearClip(0.1);
        camera.setFarClip(10000);
        camera.setFieldOfView(45);

        camera.getTransforms().addAll(
                rotateX,
                rotateY,
                cameraTranslate
        );

        cameraGroup.getChildren().add(camera);

        // Add a small axis helper
        root3D.getChildren().add(new Axis(300));

        Group sceneRoot = new Group(root3D, cameraGroup);
        SubScene subScene = new SubScene(sceneRoot, 1200, 800, true, SceneAntialiasing.BALANCED);
        subScene.setCamera(camera);

        return subScene;
    }

    private void setupControls(Scene scene, Group root3D, Node selectable) {
        // Mouse: left-drag = rotate, middle/scroll = zoom, right-drag = pan
        scene.setOnMousePressed(e -> {
            anchorX = e.getSceneX();
            anchorY = e.getSceneY();
            anchorAngleX = rotateX.getAngle();
            anchorAngleY = rotateY.getAngle();
        });

        scene.setOnMouseDragged(e -> {
            double dx = e.getSceneX() - anchorX;
            double dy = e.getSceneY() - anchorY;

            if (e.getButton() == MouseButton.PRIMARY) { // rotate
                rotateY.setAngle(anchorAngleY + dx * 0.4);
                rotateX.setAngle(anchorAngleX - dy * 0.4);
            } else if (e.getButton() == MouseButton.SECONDARY) { // pan
                cameraTranslate.setX(cameraTranslate.getX() + dx * 0.6);
                cameraTranslate.setY(cameraTranslate.getY() + dy * 0.6);
                anchorX = e.getSceneX();
                anchorY = e.getSceneY();
            }
        });

        scene.addEventHandler(ScrollEvent.SCROLL, e -> { // zoom
            double delta = e.getDeltaY();
            cameraTranslate.setZ(cameraTranslate.getZ() + (-delta) * 0.8);
        });

        scene.setOnKeyPressed(e -> {
            if (e.getCode() == KeyCode.R) {
                rotateX.setAngle(20);
                rotateY.setAngle(-45);
                cameraTranslate.setX(0);
                cameraTranslate.setY(0);
                cameraTranslate.setZ(-800);
            }
        });

        // simple gentle animation to make lighting feel alive
        AnimationTimer timer = new AnimationTimer() {
            long t0 = -1;

            @Override
            public void handle(long now) {
                if (t0 < 0) t0 = now;
                double s = ((now - t0) / 1e9) * 0.5;
                rotateY.setAngle(rotateY.getAngle() + 0.01);
            }
        };
        timer.start();
    }

    /** Build a TriangleMesh from a grid of heights. */
    private TriangleMesh buildTerrainMesh(float[][] heights, float spacing) {
        int rows = heights.length;
        int cols = heights[0].length;
        TriangleMesh mesh = new TriangleMesh();

        // vertices
        for (int r = 0; r < rows; r++) {
            for (int c = 0; c < cols; c++) {
                float x = c * spacing;
                float y = -heights[r][c] * HEIGHT_SCALE; // negative y goes up in JavaFX
                float z = r * spacing;
                mesh.getPoints().addAll(x, y, z);
            }
        }

        // texture coordinates (we'll use simple normalized coords)
        mesh.getTexCoords().addAll(0,0, 1,0, 1,1, 0,1);

        // faces (two triangles per cell)
        for (int r = 0; r < rows - 1; r++) {
            for (int c = 0; c < cols - 1; c++) {
                int p0 = r * cols + c;
                int p1 = p0 + 1;
                int p2 = p0 + cols;
                int p3 = p2 + 1;

                // triangle 1: p0, p2, p1
                mesh.getFaces().addAll(p0,0, p2,1, p1,2);
                // triangle 2: p1, p2, p3
                mesh.getFaces().addAll(p1,2, p2,1, p3,3);
            }
        }

        return mesh;
    }

    /** Generate a height grid using layered Perlin noise. */
    private float[][] generateHeightGrid(int rows, int cols, float baseFreq, int octaves) {
        float[][] h = new float[rows][cols];
        PerlinNoise pn = new PerlinNoise(12345);
        for (int r = 0; r < rows; r++) {
            for (int c = 0; c < cols; c++) {
                float nx = c * baseFreq;
                float nz = r * baseFreq;
                float amp = 1f;
                float freq = 1f;
                float sum = 0f;
                float max = 0f;
                for (int o = 0; o < octaves; o++) {
                    sum += amp * pn.noise(nx * freq, nz * freq, 0f);
                    max += amp;
                    amp *= 0.5f;
                    freq *= 2f;
                }
                sum /= max;
                // normalize to 0..1
                h[r][c] = (sum * 0.5f + 0.5f);
                // add radial island falloff for variety
                float dx = (c - cols/2f) / (cols/2f);
                float dz = (r - rows/2f) / (rows/2f);
                float d = (float)Math.sqrt(dx*dx + dz*dz);
                h[r][c] *= smoothstep(1f - d);
            }
        }
        return h;
    }

    private float smoothstep(float x) {
        x = clamp(x, 0f, 1f);
        return x * x * (3 - 2 * x);
    }

    private float clamp(float v, float a, float b) {
        return Math.max(a, Math.min(b, v));
    }

    /** Create a texture image (color map) based on heights. */
    private WritableImage buildTextureFromHeights(float[][] heights) {
        int w = heights[0].length;
        int h = heights.length;
        WritableImage img = new WritableImage(w, h);
        PixelWriter pw = img.getPixelWriter();

        for (int r = 0; r < h; r++) {
            for (int c = 0; c < w; c++) {
                float v = heights[r][c];
                Color col = heightToColor(v);
                pw.setColor(c, r, col);
            }
        }
        return img;
    }

    private Color heightToColor(float v) {
        // simple gradient: deep water -> shallow -> sand -> grass -> rock -> snow
        if (v < 0.2) return Color.color(0.03, 0.08 + v * 0.5, 0.2 + v * 0.4);
        if (v < 0.28) return Color.color(0.9, 0.86, 0.67); // sand
        if (v < 0.6) return Color.color(0.1, 0.6 - (v-0.28)*0.4, 0.13);
        if (v < 0.78) return Color.color(0.4, 0.36, 0.33);
        return Color.color(0.9, 0.9, 0.95);
    }

    /** Small axis helper Node */
    private static class Axis extends Group {
        Axis(double size) {
            final javafx.scene.shape.Box x = new javafx.scene.shape.Box(size,1,1);
            final javafx.scene.shape.Box y = new javafx.scene.shape.Box(1,size,1);
            final javafx.scene.shape.Box z = new javafx.scene.shape.Box(1,1,size);
            x.setMaterial(new PhongMaterial(Color.RED));
            y.setMaterial(new PhongMaterial(Color.GREEN));
            z.setMaterial(new PhongMaterial(Color.BLUE));
            getChildren().addAll(x,y,z);
        }
    }

    /** Simple Perlin noise implementation (3D) */
    private static class PerlinNoise {
        private final int[] perm = new int[512];

        PerlinNoise(int seed) {
            int[] p = new int[256];
            for (int i = 0; i < 256; i++) p[i] = i;
            // simple LCG shuffle
            long s = seed;
            for (int i = 255; i > 0; i--) {
                s = (s * 6364136223846793005L + 1442695040888963407L) & 0xFFFFFFFFFFFFL;
                int j = (int)(s % (i + 1));
                int tmp = p[i]; p[i] = p[j]; p[j] = tmp;
            }
            for (int i = 0; i < 512; i++) perm[i] = p[i & 255];
        }

        double fade(double t) { return t * t * t * (t * (t * 6 - 15) + 10); }
        double lerp(double t, double a, double b) { return a + t * (b - a); }
        double grad(int hash, double x, double y, double z) {
            int h = hash & 15;
            double u = h < 8 ? x : y;
            double v = h < 4 ? y : (h == 12 || h == 14 ? x : z);
            return (((h & 1) == 0) ? u : -u) + (((h & 2) == 0) ? v : -v);
        }

        public float noise(double x, double y, double z) {
            int X = (int)Math.floor(x) & 255;
            int Y = (int)Math.floor(y) & 255;
            int Z = (int)Math.floor(z) & 255;
            x -= Math.floor(x);
            y -= Math.floor(y);
            z -= Math.floor(z);
            double u = fade(x);
            double v = fade(y);
            double w = fade(z);
            int A = perm[X] + Y, AA = perm[A] + Z, AB = perm[A + 1] + Z;
            int B = perm[X + 1] + Y, BA = perm[B] + Z, BB = perm[B + 1] + Z;

            double res = lerp(w, lerp(v, lerp(u, grad(perm[AA], x, y, z),
                    grad(perm[BA], x - 1, y, z)),
                    lerp(u, grad(perm[AB], x, y - 1, z),
                            grad(perm[BB], x - 1, y - 1, z))),
                    lerp(v, lerp(u, grad(perm[AA + 1], x, y, z - 1),
                            grad(perm[BA + 1], x - 1, y, z - 1)),
                            lerp(u, grad(perm[AB + 1], x, y - 1, z - 1),
                                    grad(perm[BB + 1], x - 1, y - 1, z - 1))));
            return (float) res;
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
}
